<a href="https://colab.research.google.com/github/tomektomeknyc/tensorflow/blob/main/TensorFlow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Introduction to Tensors
### Getting info from Tensors
###Manipulating Tensors
###Tensors & Numpy
###Using @tf.function (a way to speed up your regular Python functions)
###Using GPUs with TensorFlow or TPUs
###Excercises




In [4]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


# Create tensors with tf.constant()

In [5]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#Check the number of dimensions of a tensor(ndim stands for the number of dimensions)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#Check the dimension of our vector
vector.ndim

1

In [9]:
#Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [17]:
# Create another matrix

another_matrix = tf.constant([[10., 7.],
                             [3., 2.],
                             [8.,9.]], dtype=tf.float16)
another_matrix



<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [19]:
#What's the number of dimensions of another matrix?
another_matrix.ndim

2

In [28]:
matrix3 = tf.constant([[23.,6.,3.],
                        [4.,6.,2.],
                       [54.,23.,5.],
                       [34.,56.,6.],
                       [22.,55.,6.],
                       [45.,77.,3.]])
matrix3.ndim

2